### ISSUE TITLE
Crashing due to dependency

### ISSUE THREAD

**Issue by ClayBCE** [reinderpjs/Can-You-Trash-It#1]
After installing this mod, I am getting a crash that seems to be telling me to have "team_reborn_energy" installed. Is there a way to run this mod standalone? 

```
"net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install team_reborn_energy, version 2.0.0-beta1 or later.
Unmet dependency listing:
	 - Mod 'Can You Trash It?' (cyti) 1.0.2 requires version 2.0.0-beta1 or later of team_reborn_energy, which is missing!
Inactive mods:
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 4.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 4.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.45, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: same version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Dawn API' (dawn) 3.2.0, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+65d505fc9c, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd65, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.5+65d505fc9c, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca33565, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.9+65d505fc9c, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9565, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Kyrpt Config' (kyrptconfig) 1.2.6-1.18, reason: newer version active
	 - mod 'LibGui' (libgui) 5.0.0-beta.2+1.18-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 5.1.0+1.18, reason: newer version active
	 - mod 'megane-applied-energistics-2' (megane-applied-energistics-2) 6.2.0+10.0.0-alpha.1, reason: unknown
	 - mod 'megane-dml-simulacrum' (megane-dml-simulacrum) 6.2.0+0.5.0-beta2, reason: unknown
	 - mod 'megane-extra-generators' (megane-extra-generators) 6.2.0+1.1.1-BETA-1.18, reason: unknown
	 - mod 'megane-industrial-revolution' (megane-industrial-revolution) 6.2.0+1.13.1-BETA, reason: unknown
	 - mod 'megane-kibe' (megane-kibe) 6.2.0+1.9.4-BETA-1.18, reason: unknown
	 - mod 'megane-lib-block-attributes' (megane-lib-block-attributes) 6.2.0+0.10.0, reason: unknown
	 - mod 'megane-modern-industrialization' (megane-modern-industrialization) 6.2.0+1.0.0-alpha.02, reason: unknown
	 - mod 'megane-reborn-core' (megane-reborn-core) 6.2.0+5.1.0-beta.2, reason: unknown
	 - mod 'megane-tech-reborn' (megane-tech-reborn) 6.2.0+5.1.0-beta.2, reason: unknown
	 - mod 'megane-wireless-networks' (megane-wireless-networks) 6.2.0+1.4.0, reason: unknown
	 - mod 'OmegaConfig' (omega-config) 1.0.8, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.8, reason: newer version active
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: inactive parent mod (nested jar)
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: inactive parent mod (nested jar)
	 - mod 'shulkerutils' (shulkerutils) 1.0.4-1.18, reason: same version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: newer version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: newer version active
	 - mod 'ThonkUtil' (thonkutil) 1.3, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install team_reborn_energy, version 2.0.0-beta1 or later.
Unmet dependency listing:
	 - Mod 'Can You Trash It?' (cyti) 1.0.2 requires version 2.0.0-beta1 or later of team_reborn_energy, which is missing!
Inactive mods:
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'jankson' (blue_endless_jankson) 1.2.1, reason: same version active
	 - mod 'Cardinal Components API (base)' (cardinal-components-base) 4.0.0, reason: newer version active
	 - mod 'Cardinal Components API (entities)' (cardinal-components-entity) 4.0.0, reason: newer version active
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.42, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.0.45, reason: newer version active
	 - mod 'Cloth Config v6' (cloth-config) 6.1.48, reason: same version active
	 - mod 'Cloth Config v4' (cloth-config2) 5.0.34, reason: unknown
	 - mod 'Dawn API' (dawn) 3.2.0, reason: same version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.1.3+12a8474cfa, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.0+65d505fc9c, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd65, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.5+65d505fc9c, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f3c8, reason: newer version active
	 - mod 'Fabric Lifecycle Events (v1)' (fabric-lifecycle-events-v1) 1.4.10+c15ca33565, reason: newer version active
	 - mod 'Fabric Networking API (v1)' (fabric-networking-api-v1) 1.0.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.9+65d505fc9c, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9565, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Screen API (v1)' (fabric-screen-api-v1) 1.0.7+3ac43d95c8, reason: newer version active
	 - mod 'Kyrpt Config' (kyrptconfig) 1.2.6-1.18, reason: newer version active
	 - mod 'LibGui' (libgui) 5.0.0-beta.2+1.18-rc1, reason: newer version active
	 - mod 'LibGui' (libgui) 5.1.0+1.18, reason: newer version active
	 - mod 'megane-applied-energistics-2' (megane-applied-energistics-2) 6.2.0+10.0.0-alpha.1, reason: unknown
	 - mod 'megane-dml-simulacrum' (megane-dml-simulacrum) 6.2.0+0.5.0-beta2, reason: unknown
	 - mod 'megane-extra-generators' (megane-extra-generators) 6.2.0+1.1.1-BETA-1.18, reason: unknown
	 - mod 'megane-industrial-revolution' (megane-industrial-revolution) 6.2.0+1.13.1-BETA, reason: unknown
	 - mod 'megane-kibe' (megane-kibe) 6.2.0+1.9.4-BETA-1.18, reason: unknown
	 - mod 'megane-lib-block-attributes' (megane-lib-block-attributes) 6.2.0+0.10.0, reason: unknown
	 - mod 'megane-modern-industrialization' (megane-modern-industrialization) 6.2.0+1.0.0-alpha.02, reason: unknown
	 - mod 'megane-reborn-core' (megane-reborn-core) 6.2.0+5.1.0-beta.2, reason: unknown
	 - mod 'megane-tech-reborn' (megane-tech-reborn) 6.2.0+5.1.0-beta.2, reason: unknown
	 - mod 'megane-wireless-networks' (megane-wireless-networks) 6.2.0+1.4.0, reason: unknown
	 - mod 'OmegaConfig' (omega-config) 1.0.8, reason: newer version active
	 - mod 'OmegaConfig' (omega-config) 1.0.8, reason: newer version active
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: inactive parent mod (nested jar)
	 - mod 'lambdajcommon' (org_aperlambda_lambdajcommon) 1.8.1, reason: inactive parent mod (nested jar)
	 - mod 'shulkerutils' (shulkerutils) 1.0.4-1.18, reason: same version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: newer version active
	 - mod 'SpruceUI' (spruceui) 3.3.0+1.17, reason: newer version active
	 - mod 'ThonkUtil' (thonkutil) 1.3, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
"
```

**Comment by reinderpjs** [comment]
I uploaded a new version (1.0.3) which no longer needs the energy api as a dependency so it should work now!
